### ISSUE TITLE
Search not working correctly with pagination

### ISSUE THREAD

**Issue by smchristensen** [rnwood/smtp4dev#1373]
When I use the search functionality, the emails are not filtered properly and requires using the pagination to find emails matching the search criteria.

As an example, suppose I have pagination set to 30 items per page sorted by newest received date and have 50 emails in smtp4dev.  If the 36th email contains my search criteria and I'm on page 1, using the search filter will show page 1 without any emails and I have to navigate to page 2 in order to see the email that does match the search criteria.

**Comment by rnwood** [comment]
Thanks for your feedback. 

That's right. It currently filters the current view/page only and it's done client side. This implementation was ok when originally all message headers were loaded, but it's odd/unexpected since paging has been added.

I agree that this is something that can be improved.

**Comment by rnwood** [comment]
A change to move search to the server side has been done in PR #1375.

One of the current side effects is that  (since SQLite doesn't support it with defaults) the case insensitivity will only apply to characters in the ASCII range.

I'd like to resolve this before merging if possible. Since it will affect many smtp4dev international users.
