### ISSUE TITLE
[Bug] Re-introduce 'allow any credentials' mode for SMTP

### ISSUE THREAD

**Issue by ahmed2m** [rnwood/smtp4dev#1425]
If I understand correctly and how it was working before (but not anymore) connections are refused if they have a user/password when the authentication is off (default).

Currently on 3.3.6. and the "Configuring Clients" wiki page says: "Authentication is not required, but will be accepted if your client insists on their configuration"

**Comment by rnwood** [comment]
Thanks for pointing out this regression in features and docs that need to be updated.
I think this is important because some clients will insist on authenticating even if the server isn't offering it.

Currently if the require auth setting is off, smtp4dev doesn't advertise auth at all. The client will fail it insists on trying anyway.

I will add a new `Allow authentication` setting that defaults to on to match the old behaviour. So the server will advertise auth by default.

I will also add a `Allow any credentials` / `Use configured users` switch with it defaulting to the former. So the server will accept any username/password combination by default.

**Comment by rnwood** [comment]
PR #1428
