### ISSUE TITLE
[Feature] Support SMTP AUTH authentication with whitelist of allowed credentials

### ISSUE THREAD

**Issue by mcattabiani** [rnwood/smtp4dev#161]
How do I make authorization mandatory?
I tried to implement a new SmptServer with the associated behavior that exposes "AuthExtension".
If I send the ehlo command, it does not expose the authentication.
How can I do?
Thank you

**Comment by rnwood** [comment]
Thanks for your question. Auth is supported in the server component that Smtp4dev uses and was exposed in the v2 Windows UI. It isn't yet exposed in the new v3 Web UI.

**Comment by rnwood** [comment]
Basic support has now been added to turn on AUTH. All supported AUTH mechanisms (CRAMMD5, PLAIN, LOGIN, ANONYMOUS) will be accepted and any credentials will be accepted.
This needs to be extended so that a list of credentials can be configured and so that the server will only accept the configured list.

**Comment by faddiv** [comment]
Hy wood,
I'm working on this since I also need this feature.
If you are interested I can send a pull request when I finished. Also, I'm interested in your suggestion, on how I should implement this if my current implementation is wrong. You can check it in my repo.

**Comment by katevi** [comment]
Hi! Any updates on this feature? :)

**Comment by rnwood** [comment]
Something simple but flexible has been implemented which allows controlling the auth result via rules.
See `AuthenticationRequired` and `CredentialsValidationExpression` in the appsettings.
