### ISSUE TITLE
Newest docker image doesn't run (missing dependency)

### ISSUE THREAD

**Issue by asys-bstz** [rnwood/smtp4dev#169]
Hi,

running the newest docker image gives the following output:

```
smtp      | It was not possible to find any compatible framework version
smtp      | The specified framework 'Microsoft.AspNetCore.App', version '2.2.6' was not found.
smtp      |   - Check application dependencies and target a framework version installed at:
smtp      |       /usr/share/dotnet/
smtp      |   - Installing .NET Core prerequisites might help resolve this problem:
smtp      |       https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
smtp      |   - The .NET Core framework and SDK can be installed from:
smtp      |       https://aka.ms/dotnet-download
smtp      |   - The following versions are installed:
smtp      |       2.2.4 at [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
```

It seems the dependabot incremented the version from `2.2.4` to `2.2.6`, but the Dockerfile still [references `2.2.4`](https://github.com/rnwood/smtp4dev/blob/master/Dockerfile.linux#L47).

Downgrading to `linux-amd64-3.1.0-ci0736` makes it all work again.

**Comment by rnwood** [comment]
Thanks for reporting this.

I'll merge the quick fix #171 that andrewdavey has kindly contributed. Then to ensure this doesn't happen again:

- [ ] the E2E tests need to be run for the docker image build so that it will fail if there's no matching runtime.
- [ ] the build script should read version of Microsoft.AspNetCore.App package dependency and pass into the docker build process as a param, so that the version of the runtime we're targetting is only maintained in one place.

**Comment by rnwood** [comment]
Just to confirm that the quick fix is in place and I've tested the latest tagged Docker images no longer have this issue.

**Comment by asys-bstz** [comment]
Can confirm, thanks.
