### ISSUE TITLE
[DockerHub] Tag latest image with tag "latest"

### ISSUE THREAD

**Issue by tiesmaster** [rnwood/smtp4dev#192]
For of all, this is really an amazing tool, I've been using it for years, and really nice that you've taken the effort to port it to Core ;)

I'm using the docker image from DockerHub, however, I'd want to pull in "just the latest" image. Now, I have a reference to `rnwood/smtp4dev:linux-amd64-3.1.0-ci0706` in my `docker-compose.yml` file, however, it'd be nice if I could drop the version tag, and rely on the tooling to take the latest.

Is this a possibility to add?

**Comment by rnwood** [comment]
Hi

You can use the label `linux-amd64-v3` to achieve what you want for now. This will track the latest available image and should work until (if ever) there's a v4.x.

I'd like to create a `latest `label, but because the images we're producing target both Windows and and Linux, it requires a special step in the build process to create a label which referencing the latest image for each architecture. This is quite complex with the current appveyor build process, and at the moment I don't have the appetite to address this one. 

PRs welcome if anybody reading this would like to have a go.

Thanks
Rob

**Comment by rnwood** [comment]
This has now been implemented.

**Comment by tiesmaster** [comment]
Awesome! Works like a charm ❤️
