### ISSUE TITLE
Problem to work with Smtp4dev

### ISSUE THREAD

**Issue by Eric-At-Advantech** [rnwood/smtp4dev#308]
An error occurred while attempting to establish an SSL or TLS connection. The SSL certificate presented by the server is not trusted by the system for one or more of the following reasons: 1. The server is using a self-signed certificate which cannot be verified. 2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate. 3. The certificate presented by the server is expired or invalid. See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#InvalidSslCertificate for possible solutions.

**Comment by rnwood** [comment]
There are now some brief instructions printed on startup that should help. TLS has also been disabled by default to help people avoid needing to go through this unless needed.

1) You need to make sure that you connect to smtp4dev with the same hostname that is specified in `ServerOptions.HostName` in `appsettings.json` (`localhost` by default). If you are connecting from remote machines, you will need to change this to the DNS name of the machine and then ensure that the client uses the exact same name when connecting (e.g. `mymachine.mydomain` is not the same as `mymachine`). This is because clients verify the name presented in the certificate and check it's the same as the host they tried to connect to.

2) You need to make sure the client (the program connecting to smtp4dev) trusts the certificate that is being used. This is an automatically generated self-signed cert unless you've supplied one. The startup prints out the name of the file where you can grab it. You then need to follow instructions depending on the client and OS. For most clients running on W10 there are some instructions you can see here:
https://www.thewindowsclub.com/manage-trusted-root-certificates-windows
