### ISSUE TITLE
Difficulties working with IIS

### ISSUE THREAD

**Issue by dougwaldron** [rnwood/smtp4dev#309]
I successfully have smtp4dev running as a service on my web server, and emails are being stored in the Sqlite database. (I know this from inspecting the database.) Now I'm trying to make the website available using IIS, and have encountered several problems.

First, if I point IIS to the root folder of smtp4dev, it fails to start with this error message:

> "Application startup exception: System.Net.Sockets.SocketException (10048): Only one usage of each socket address (protocol/network address/port) is normally permitted."

I assume because it's already running as a service? But if I stop the service and only run in IIS, it no longer captures emails.

I also tried pointing IIS to the wwwroot folder. The website works then, but doesn't display any messages.

Finally, unrelated to the above, if I run as a subfolder in IIS, Vue.js doesn't work because the css & js links point to the root. See [this StackOverflow post](https://stackoverflow.com/questions/58815615/how-to-build-vue-js-for-subfolder) for a good description of the problem. 

I edited the index.html file to change the links to be relative, but it still doesn't work; it just shows a blank page.

**Comment by guitarzan** [comment]
So I found out I can install a second copy of smtp4dev and point both to the same database -- one acts as the SMTP server (running as a Windows service), and the other acts as a web interface to view the emails. I expect eventually I might run into database conflicts between the two.

So am I completely misunderstanding how this app is intended to be used? It works fine running locally as both SMTP server and web app (both on localhost), but I'd like to be able to use it on my dev server so that I can test email functionality without connecting to a "real"/external SMTP server. But for this to be reasonable, the web app needs to be available through IIS. Is there a way to accomplish this? 

Thanks.

**Comment by zemien** [comment]
Hi, I'm not the developer but I was reading your issue and wondered why you said "But for this to be reasonable, the web app needs to be available through IIS. "

From my limited time using this, I can see the application creates a Kestrel process to host the web app. Kestrel is a lightweight web server, while IIS is a fully-featured web server. What do you need from IIS that you're not getting from Kestrel?

**Comment by zemien** [comment]
Oh wait, did you mean "dev server" as in setting it up as a long-running service on a server that all developers point to? I don't think it's meant to be used that way. I would recommend each developer having this running on their own localhost environments since this is a lightweight process. This also means the developer only sees their own emails on the web app, rather than emails that could have been generated by other devs.

**Comment by guitarzan** [comment]
@zemien Yes, that's what I meant. I understand this is mainly intended for use in local development, and it works great for that. But occasionally, we need to test on a deployed web server for various reasons, and that means running the risk of generating confusing emails sent to non-testers.

**Comment by guitarzan** [comment]
I've made progress on this. Initially, I was deploying smtp4dev as an application under the Default Web Site, and that didn't work. Smpt4dev wouldn't listen on the SMTP port.

So instead I deployed it as its own web site with its own application pool following the [Microsoft Docs](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-3.1#create-the-iis-site), and that works great. It receives all email and is available over IIS.

The only problem now is that the web app doesn't seem to be able to update the database. When I try to delete a message, it returns a 405 Method Not Allowed:

<img width="377" alt="Screen Shot 2020-04-07 at 4 06 58 PM" src="https://user-images.githubusercontent.com/737326/78784151-d54c4700-7972-11ea-83b0-fffc98668c41.png">

**Comment by zemien** [comment]
Hi Doug

Ok I get your use case but I still don’t understand why it must be on IIS?

I thought you managed to install the original app (running Kestrel) as a
service. That should mean it’s running in the background available for
anyone to call into.

Your error message relates to IIS configuration rather than the app itself.
There’s a setting in IIS to configure which http methods are allowed.

Again, I suspect you might be complicating things for yourself by not using
the service as it is.

**Comment by guitarzan** [comment]
@zemien I have no doubt that I am over-complicating things! I'm no IIS expert.

Yes, I can run the app as a service (or directly from the .exe), but IIS is running so don't any web connections have to go through IIS?

I didn't know about configuring IIS to allow methods. I found a place to allow/disallow HTTP verbs under request filtering, but no verbs are blocked. Even when I explicitly allow "DELETE", I get the same 405 status code.

**Comment by zemien** [comment]
Ahh I see where you're coming from. You'll be glad to know that web connections *don't* have to go through IIS. There are different software capable of serving web connections besides IIS, such as Apache Tomcat, nginx, and Kestrel (which is what smtp4dev uses).

Once you've run the app, either service or .exe, it will be available to receive network requests. Now, you may need to allow inbound rules on the server firewall since the default web app port 5000 is not usually exposed. 

You will conflict with IIS if you want to run it on port 80/443. In that case you have to stop the websites in IIS running on that port, usually the Default Web Site, so that Kestrel can bind to those. Again, ports 80/443 are the usual ports for website but there's nothing stopping you from running it on other free ports. The developers just need to specify the relevant port when browsing to it, e.g. http://dev-smtp:5000

Good luck!

**Comment by guitarzan** [comment]
Thanks a lot for the help! I didn't know that about Kestrel/IIS. Unfortunately, I think only 80 & 443 are open. But it sounds like opening an alternate port is the best way forward.

**Comment by chz160** [comment]
@guitarzan I think am using smtp4dev in similar manner as it sounds like you are. I have my test environment servers pointed to one instance of smtp4dev. This is to keep any emails from our test environments from actually going anyplace and we can access the smtp4dev web interface and see that our applications email output was correct.

What I wanted to add was, that in order for smtp4dev's self hosted website to be accessible from anything other than the hosting server's loopback address you must execute the exe with the following option: 

`--server.urls "http://0.0.0.0:5000/"`

Otherwise you will not be able to access the site from another machine.
