### ISSUE TITLE
Allow full file path for Database file.

### ISSUE THREAD

**Issue by TylerRudie** [rnwood/smtp4dev#541]
The setting for the sqllite databae is 'stored relative to APPDATA env var' on windows. It is generally accepted that stuffing large amounts of data in the users profile is bad. Let alone if the application is running as 'Local System' when running as a service.

**Comment by rnwood** [comment]
This is already possible. Either absolute paths or relative paths will work as value for `Database` in `appsettings.json`, via the corresponding `ServerOptions:Database` env var or using `--db` command line argument. If you specify a relative path it is resolved relative to the data directory which is at `%APPDATA%\smtp4dev`.

I will resolve this in the documentation/help as this is currently incorrect and also make clear that absolute paths are accepted too.

Re comments about stuffing large amounts of data in 'profile' being a bad idea. What is your suggestion? 
Should we use `%LOCALAPPDATA%` instead to be kind to users with roaming profiles?

How should our service registration documentation differ (run as LocalService instead?). Can you contribute how to change the commands in the documentation to achieve this?

**Comment by TooMuchBlue** [comment]
I ran into this issue as well and found this closed ticket.

One of the concerns I have about storing it in %APPDATA% is that Windows makes it hard to find or inspect this folder.  The default APPDATA folders for service accounts live under C:\Windows\System32\ServiceProfiles, and trying to access this folder requires an elevated permissions grant.  ("You don't currently have permission to access this folder. Click Continue to permanently get access to this folder.")

If I want to update the appsettings.json file in a way that won't be overwritten by updates, I have to grant myself access to that folder, or run it under my own account.  Not so handy for a shared web server.

I would suggest a command-line parameter that provides the base path for finding the user-preferred appsettings.json file, and possibly (at your discretion) also the path for the database, predefined/autogenerated certificates, and so on.  For my use case, this would make the installation process much more consistent across clients, and protect local settings against overwrites when updating (unzip everything over the top of the existing install, because all the files live elsewhere).

I'm happy to brainstorm further if some of this doesn't fit your ideas for how it should work.
