### ISSUE TITLE
IIS setup instructions are not clear

### ISSUE THREAD

**Issue by jeffjmc** [rnwood/smtp4dev#658]
Hello,
   Could you expand on the details of getting smtp4dev working under IIS?    
I have unzipped the x64 zip to my inetpub folder (where all of my other applications are running) and created an IIS application that points to C:\inetpub\Smtp4dev\wwwroot.   I am not sure if this is correct.  From the current instructions, it seems like I should be pointing the IIS application's physical path to the root of the unzipped folder ( C:\inetpub\Smtp4dev ) which IIS doesn't seem to like.

with my current setup in IIS I can bring up the smtp4dev page and it looks ok.   however, if I do a telnet connection test to the smtpPort I have configured in the appsettings.json file (5252) the connection is rejected.

if I manually start smtp4dev using the exe. I can telnet connect to the configured port.

So I think I somehow missed a step that would tell IIS to start the exe?  or do I need to be running smtp4dev as a service first?

Running smtp4dev 3.1.2

Thanks for building smtp4dev!!

**Comment by rnwood** [comment]
You should be able to see the status of the SMTP server at the top right of the window. It should normally say 'SMTP server running on port X'. If there's was an error starting this it will be shown here.

**Comment by jafin** [comment]
@jeffjmc ,  I did the following to start up under IIS:

* Unzip smtp4dev contents.
* Create new site in IIS and point the root folder to where the web.config is for your unpacked smtp4dev.
* Set AppPool to NETCore (No Managed CLR).
* Set port and start

Connect to the UI should be good.

## Some Challenges

### Write Permission
Note: On one server, which was locked down, I had to explicitly grant permission to the IIS account to have write access to the folder so it could write to database.db  Mayby check that?

### Idle Timeout/Apppool recycle.
Also note, you need to touch the UI to activate the app, otherwise it will not of been started and therefore not registered on your SMTP port.  Unless you have something that warms up your app/autostarts it automatically.

Also be aware similar issue, apppool recycles and idle timeouts under IIS can stop the server running. 

For these reasons I don't think it is ideal to run this server under IIS.

**Comment by rnwood** [comment]
Hi thanks for feeding back on this.

I've updated the instructions a bit here:
https://github.com/rnwood/smtp4dev/wiki/Installation

This includes setting the app to always stay running without automatic recycles and idle timeout.

I have also made a change to improve the included `web.config` so that IIS will start up smtp4dev without needing the first request to be received.

**Comment by rnwood** [comment]
Closing for now. Feel free to re-open if I've missed anything.
