### ISSUE TITLE
Release builds (triggered by manually applied git label) are not being tagged correctly on Docker hub

### ISSUE THREAD

**Issue by satanTime** [rnwood/smtp4dev#695]
Hi,

thanks for the awesome app. I see that 3.1.2 have been released, but cannot find its image on docker hub. Could you build and publish it?

Thanks!

**Comment by rnwood** [comment]
I've looked into this and it's because of a bug in the CI/release process. I will keep this ticket open to fix this or it will also affect next releases.

I have manually tagged the image for 3.1.2. So you'll be able to find this now.

________________________________
From: MG. ***@***.***>
Sent: Wednesday, 21 April 2021, 15:40
To: rnwood/smtp4dev
Cc: Subscribed
Subject: [rnwood/smtp4dev] Publish 3.1.2 on docker hub (#695)


Hi,

thanks for the awesome app. I see that 3.1.2 have been released, but cannot find its image on docker hub. Could you build and publish it?

Thanks!

**Comment by satanTime** [comment]
Just a note, the published docker image for 3.1.2 contains only windows platform, whereas I use linux.
