### ISSUE TITLE
Date-time stored in local timezone but exposed without timezone indication

### ISSUE THREAD

**Issue by eanon** [rnwood/smtp4dev#807]
Hello,

As complement to what I posted in the issue tracker of a side project called smtp4devpy (see [here](https://github.com/plentific/smtp4devpy/issues/2)), I have some questions about the way date-time strings are used in smtp4dev... Maybe it's voluntary, maybe not, but here are my observations:

First, I saw that the time is displayed in local time in the webmail UI: perfect!, I think it's a good idea... But, where I was surprised is that these date-time strings are stored in local time too in the database. Of course, you indicate the offset at the end of the string, but it would be far easier to just store UTC time, then convert for display only...

As second point, and primarily since I tried to understand an issue with this side project I'm talking about above (smtp4devpy), I saw that hitting http://localhost:5000/api/Messages?sortColumn=receivedDate&sortIsDescending=true, you return a receivedDate in local time without any offset indication. So, the author of smtp4devpy thought it was a GMT one, while it's not.

Well, nothing important, but nothing difficult to fix too.
It was my two cents, and Bravo! for smtp4dev.

**Comment by rnwood** [comment]
Now available in latest pre-release.

Thanks to @jafin, the dates are now converted and stored in UTC in the DB; although still without an offset or Z to make it clear because of a limitation in SQLLite and EF ORM. To plug this gap he has also ensured that they are explicity marked as UTC dates after reading from the DB so the (undocumented private(ish)) API they are using in smtp4devpy returns the correct offset/specifier.
